# Preparing for a Research Cruise {#cruise_prep}

Planning for a cruise begins several months before it sails.

## Spatial Data Preparation
- Create a single .kml file that includes all planned instrument retrievals and any planned additional deployments and other necessary points (collectively all called “planning points”. .kml files are more agile than ArcGIS files; they are easier to use in Google Earth for day to day planning.
- Create an ArcGIS map project that contains the locations of all planning points.

## Garmin 78 Handheld GPS Preparation
- Ensure each handheld unit is setup properly
  - Time to UTC
  - LAT and LONG in decimal degrees
- Test each handheld GPS to be taken on the cruise prior to sailing: take it outside and ensure that it collects waypoints.
- Upload planning points to both the primary and secondary GPS units.

## Datasheet Preparation

* Prepare Field Data Binders
  + Print enough data sheets for all activities, including mooring, CAU, CTD/H2O for the OCC team in addition to enough CTD/H20 data sheets for any other team on CTD/H20 Ops.
  + Attach sharp pencils to field binders

## Software Needed at Sea

| Software                                | Team Lead Only | Manufacturer      | Needed For                                         | Instrument           | Download Location                                                                    |
|-----------------------------------------|----------------|-------------------|----------------------------------------------------|----------------------|--------------------------------------------------------------------------------------|
| ARCMap                                  | x              | ESRI              | planning operations and generating maps            | NA                   | see Tomoko                                                                           |
| Google Earth                            |                | Google            | planning operations                                | NA                   |                                                                                      |
| Keyspan USA Software                    |                | Keyspan           | serial to USB adapter cable                        | GPS                  | https://www.tripplite.com/support/USA19HS                                            |
| Microsoft Access 2010                   |                | Microsoft         | mooring and CTD databases                          | NA                   | request from ITS                                                                     |
| Excel                                   |                | Microsoft         | spreadsheets                                       | NA                   | you must have this already                                                           |
| DNR Garmin                              |                | Minnesota DNR     | download of GPS Waypoints                          | GPS                  | http://www.dnr.state.mn.us/mis/gis/tools/arcview/extensions/DNRGarmin/DNRGarmin.html |
| DNR GPS                                 |                | Minnesota DNR     | upload of GPS planning points from Google Earth    | GPS                  | http://www.dnr.state.mn.us/mis/gis/DNRGPS/DNRGPS.html                                |
| Aquadopp Software - AquaPro v1.37.08    |                | Nortek            | instrument interface                               | Aquadopp ADCP        | http://www.nortek-as.com/en/support/software                                         |
| SoundTrap Host Software Version 2.0.9.x | x              | Ocean Instruments | instrument interface                               | Sound Trap           | http://www.oceaninstruments.co.nz/downloads/                                         |
| Basic Stamp Editor                      |                | Paralax Inc.      | instrument interface                               | PUC                  | https://www.parallax.com/downloads/basic-stamp-editor-software-windows               |
| Python 2.51                             |                | Python            | scripts that are part of mooring and CTD databases | NA                   | https://www.python.org/download/releases/2.5.1/                                      |
| SeaFETCOM 2                             |                | Satlantic         | instrument interface                               | SeaFet               | http://satlantic.com/seafetcom                                                       |
| Seaterm 1.59                            |                | SeaBird           | instrument interface                               | SBE39, SBE19, SBE19+ | http://www.seabird.com/software/software                                             |
| Seaterm V2                              |                | SeaBird           | instrument interface                               | sbe19+ V2, SBE56     | http://www.seabird.com/software/software                                             |
| SBE Data Processing                     |                | SeaBird           | CTD cast processing                                | SBE CTDs             | https://www.seabird.com/software-updates                                             |
| R and R Studio for STR processing       |                | R Studio          | data processing                                    | all                  | https://www.rstudio.com/products/rstudio/download/                                   |
| Ruskin                                  |                | RBR               | STR, PAR, DO                                       | RBR Solo             | https://rbr-global.com/products/software                                             |


