# Software Needed at Sea

| Software                                | Team Lead Only | Manufacturer      | Needed For                                         | Instrument           | Download Location                                                                    |
|-----------------------------------------|----------------|-------------------|----------------------------------------------------|----------------------|--------------------------------------------------------------------------------------|
| ARCMap                                  | x              | ESRI              | planning operations and generating maps            | NA                   | see Tomoko                                                                           |
| Google Earth                            |                | Google            | planning operations                                | NA                   |                                                                                      |
| Keyspan USA Software                    |                | Keyspan           | serial to USB adapter cable                        | GPS                  | https://www.tripplite.com/support/USA19HS                                            |
| Microsoft Access 2010                   |                | Microsoft         | mooring and CTD databases                          | NA                   | request from ITS                                                                     |
| Excel                                   |                | Microsoft         | spreadsheets                                       | NA                   | you must have this already                                                           |
| DNR Garmin                              |                | Minnesota DNR     | download of GPS Waypoints                          | GPS                  | http://www.dnr.state.mn.us/mis/gis/tools/arcview/extensions/DNRGarmin/DNRGarmin.html |
| DNR GPS                                 |                | Minnesota DNR     | upload of GPS planning points from Google Earth    | GPS                  | http://www.dnr.state.mn.us/mis/gis/DNRGPS/DNRGPS.html                                |
| Aquadopp Software - AquaPro v1.37.08    |                | Nortek            | instrument interface                               | Aquadopp ADCP        | http://www.nortek-as.com/en/support/software                                         |
| SoundTrap Host Software Version 2.0.9.x | x              | Ocean Instruments | instrument interface                               | Sound Trap           | http://www.oceaninstruments.co.nz/downloads/                                         |
| Basic Stamp Editor                      |                | Paralax Inc.      | instrument interface                               | PUC                  | https://www.parallax.com/downloads/basic-stamp-editor-software-windows               |
| Python 2.51                             |                | Python            | scripts that are part of mooring and CTD databases | NA                   | https://www.python.org/download/releases/2.5.1/                                      |
| SeaFETCOM 2                             |                | Satlantic         | instrument interface                               | SeaFet               | http://satlantic.com/seafetcom                                                       |
| Seaterm 1.59                            |                | SeaBird           | instrument interface                               | SBE39, SBE19, SBE19+ | http://www.seabird.com/software/software                                             |
| Seaterm V2                              |                | SeaBird           | instrument interface                               | sbe19+ V2, SBE56     | http://www.seabird.com/software/software                                             |
| SBE Data Processing                     |                | SeaBird           | CTD cast processing                                | SBE CTDs             | https://www.seabird.com/software-updates                                             |
| R and R Studio for STR processing       |                | R Studio          | data processing                                    | all                  | https://www.rstudio.com/products/rstudio/download/                                   |
| Ruskin                                  |                | RBR               | STR, PAR, DO                                       | RBR Solo             | https://rbr-global.com/products/software                                             |
