# Tasks at Sea {#tasks}

## Daily Tasks for the Team

[Find Excel version here via Google Drive](https://drive.google.com/open?id=1I4Hojo0qjKtUwhRqgc9aLM6_fGtjqZMM)


**STR**

* Before Ops
  + assemble, program and stage needed STRs 
  + confirm 10 36'' cable ties for each STR planned
  + write serial numbers of planned STR deployments on tomorrow's data sheet
* After Ops
  + download strs
  + enter deployments and retreivals into mooring database
  + import waypoints into mooring database
  + clean STRs, put weights and brackets on fantail or in DD bath

**CAU**

* Before Ops
  + Pack supplies for planned CAU site swaps
  + write down deploy CAU SNs on tomorrow's data sheet

* After Ops
  + scrape/record CAU SN's, re-bag and freeze with cruise & site label
  + dispose of old clips and stakes
  + after CTD/H2O data is entered, give data sheets to data manager

**Water Sampling and CTD**

* Before Ops
  + DIC bottles and all supplies in each kit
  + Niskin, line, messenger, weight staged for each CTD

* After Ops
  + rinse and stage CTDs
  + Swap full bottles for empties, dispose of waste
  + restock all supplies
  + replace and label any worn ziplocs
  + enter CTD and water sample log into CTD/H2O Database (hopefully this is not a necessary step on MARAMP 2020!)

**GPS Units (for OCC and benthic/fish GPS)**

* Drop off GPS units with data manager for waypoiont download

**Cameras**

* Before Ops
  + Ensure cameras are set to UTC time
  + Ensure cameras have memory cards
  + charge camera batteries
  + clean camera housings
  + bake desiccants and install them
* After Ops
  + download and sort photos
  + download and sort photoquad photos
  + charge cameras or swap charged batts for used batts
  + install new dessicants

**Stage all Gear**

* Action packer packed for day of ops
* Pam float and reel staged
* If deep STR: Marker Float and drop weight
* 1 full bag of large cable ties (keep on boat)
* CTDs and lines

**Other**

* gauge tanks

**Team Lead**

* Plan tomorrow's objectives
* Plan and communicate tank needs to team members

## Where to Save Data

[Checkout this Excel file on Google Drive for details on where to save data](https://drive.google.com/open?id=16l1OQgGEunLoADh_MEGyIfbQL2w0u6aw)
